server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2_server?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: sqlzyydxe
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
check-user-scopes: true
